name: 'QC benchmark action'
description: 'Perform a scientific QC benchmark consisting of data download and result evaluation'
inputs:
  task: 
    description: Task to perform. Either 'download' or 'eval'.
    required: true
  benchmark-name:
    description: Name of the benchmark to conduct
    required: true
  results-path:
    description: Path to results that shall be benchmarked
runs:
  using: node12
  main: src/main.js