name: 'QC benchmark action'
description: 'Perform a scientific QC benchmark consisting of data download and result evaluation'

branding:
  icon: check
  color: green

inputs:
  task: 
    description: task to perform; either 'download' or 'eval'
    required: true
  benchmark_name:
    description: name of the benchmark to conduct
    required: true
  results_path:
    description: path to results that shall be benchmarked
  args:
    description: additional arguments for the given task

outputs:
  report:
    description: path to report of evaluation results (a directory or a file, depending on the benchmark)
  data:
    description: path to benchmark data

runs:
  using: node12
  main: src/main.js
